Repository Microsoft/ProcDump-for-Linux, pull requests merged in 2018-10, with the labels that each got.

#34 Implement waiting for process by name (-w parameter)
  Makefile
  README.md
  include/ProcDumpConfiguration.h
  src/ProcDumpConfiguration.c
  src/Procdump.c
  tests/integration/ProcDumpTestApplication.c
  tests/integration/runProcDumpAndValidate.sh
  tests/integration/scenarios/high_cpu_by_name.sh
  tests/integration/scenarios/low_cpu_by_name.sh
Labels: new feature

#43 Consolidating all development into master branch to simplify contribution
  CONTRIBUTING.md
  Makefile
  README.md
  include/ProcDumpConfiguration.h
  src/ProcDumpConfiguration.c
  src/Procdump.c
  tests/integration/ProcDumpTestApplication.c
  tests/integration/runProcDumpAndValidate.sh
  tests/integration/scenarios/high_cpu_by_name.sh
  tests/integration/scenarios/low_cpu_by_name.sh
Labels: infrastructure

#40 Document -w parameter in manpage (fix for #34)
  procdump.1
Labels: documentation
